name: YAML Test file

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: List contents
        run: ls

      - name: Compile classes
        run: |
          mkdir -p ./bin
          javac -d ./bin -cp "./testresources/junit-platform-console-standalone-1.9.2.jar" ./src/POEPart3/POEPart3.IT.java ./src/POEPart3/POEPart3ITTest.java ./test/POEPart3/POEPart3.ITTest.java ./test/POEPart3/POEPart3ITTest.java

      - name: List contents of bin directory after compile
        run: ls ./bin/POEPart3

      - name: Run POEPart3.ITTest and create report
        run: |
          ls ./bin
          java -jar ./testresources/junit-platform-console-standalone-1.9.2.jar -cp ./bin --select-class POEPart3.POEPart3.ITTest

      - name: Run POEPart3ITTest and create report
        run: |
          ls ./bin
          java -jar ./testresources/junit-platform-console-standalone-1.9.2.jar -cp ./bin --select-class POEPart3.POEPart3ITTest
